Repository ModellingWebLab/WebLab, pull requests merged in 2018-11, with the labels that each got.

#83 [WIP] Per-version entity visibility
  weblab/.codecov.yml
  weblab/config/settings/base.py
  weblab/conftest.py
  weblab/core/models.py
  weblab/core/recipes.py
  weblab/core/tests/__init__.py
  weblab/core/tests/test_models.py
  weblab/core/tests/test_visibility.py
  weblab/core/visibility.py
  weblab/entities/forms.py
  weblab/entities/migrations/0009_remove_entity_visibility.py
  weblab/entities/models.py
  weblab/entities/repository.py
  weblab/entities/templatetags/entities.py
  weblab/entities/tests/test_models.py
  weblab/entities/tests/test_repository.py
  weblab/entities/tests/test_templatetags.py
  weblab/entities/tests/test_views.py
  weblab/entities/urls.py
  weblab/entities/views.py
  weblab/experiments/managers.py
  weblab/experiments/models.py
  weblab/experiments/tests/test_models.py
  weblab/experiments/tests/test_views.py
  weblab/experiments/views.py
  weblab/repocache/__init__.py
  weblab/repocache/admin.py
  weblab/repocache/apps.py
  weblab/repocache/entities.py
  weblab/repocache/exceptions.py
  weblab/repocache/management/__init__.py
  weblab/repocache/management/commands/__init__.py
  weblab/repocache/management/commands/populate_entity_cache.py
  weblab/repocache/migrations/0001_initial.py
  weblab/repocache/migrations/0002_cachedentityversion_timestamp.py
  weblab/repocache/migrations/0003_auto_20181012_1337.py
  weblab/repocache/migrations/0004_auto_20181015_1620.py
  weblab/repocache/migrations/__init__.py
  weblab/repocache/models.py
  weblab/repocache/populate.py
  weblab/repocache/tests/__init__.py
  weblab/repocache/tests/test_commands.py
  weblab/repocache/tests/test_entities.py
  weblab/repocache/tests/test_models.py
  weblab/repocache/tests/test_populate.py
  weblab/static/js/entity.js
  weblab/templates/entities/entity_tag_version.html
  weblab/templates/entities/entity_version.html
  weblab/templates/entities/entity_version_compare.html
  weblab/templates/entities/entity_versions.html
  weblab/templates/entities/includes/version_files.html
  weblab/templates/entities/includes/version_name.html
Labels: in progress

#86 Remove javascript for displaying entity version
  weblab/static/js/entity.js
  weblab/static/js/experiment.js
Labels: in progress

#88 Add visibility field to new version form
  weblab/entities/forms.py
  weblab/entities/tests/test_views.py
  weblab/entities/views.py
Labels: bug, review

#92 Fix archive download for non-latest versions
  weblab/core/combine.py
  weblab/core/tests/test_combine.py
  weblab/entities/repository.py
  weblab/entities/tests/test_repository.py
Labels: in progress

#90 Fix javascript on the experiment page
  weblab/static/js/entity.js
  weblab/static/js/experiment.js
  weblab/static/js/main.js
Labels: review

#89 Entity fixes
  weblab/entities/tests/test_views.py
  weblab/entities/views.py
  weblab/repocache/migrations/0005_auto_20181116_1433.py
  weblab/repocache/models.py
Labels: review
